### ISSUE TITLE
Unable to run in Xcode

### ISSUE THREAD

**Issue by latne1ec** [andrewnakas/ARKit-Cardboard-VR#1]
This is awesome. Been trying to get this to work myself. 

Running into some trouble when building for Xcode though. I'm getting multiple Apple Match-O Linker errors in the workspace project after building from Unity. 

I've tried updating the pod to the latest GoogleVR as described on their repo but still no luck. Any idea what's going on?

**Comment by andrewnakas** [comment]
Hmm, can you build a normal ar project? I'll add some installation help to the readme forsure. 

you need all the basic stuff for arkit which you can grab here.
https://forum.unity3d.com/threads/arkit-support-for-ios-via-unity-arkit-plugin.474385/ 
ios 11
xcode 9 beta 2
unity 5.6.1 p 1
and you also need t make sure camera permissions is setup.

**Comment by latne1ec** [comment]
Yeah I've been building a few ARKit projects, I think it's a GoogleVR issue.

Are you enabling "Virtual Reality Supported" in Unity Player settings and adding the Cardboard SDK?

What GVRSDK pod version are you using?

**Comment by andrewnakas** [comment]
I definitely need to make that more clear, I'm using gvr .85 which is the last one before they required native support.  You should be able to load it up, build it, just make sure to leave vr supported unchecked. I possibly think I could try to get it working with the latest version but i suspect the render texture hack I use for ar and tracking in general would be harder to implement.

**Comment by andrewnakas** [comment]
Ok I got the issue fixed and pushed a solution. There is zip file that you need to uncompress in iOS plugins that is too big to upload to git. Due to the file being missing it was causing those linker errors. Sorry about that. The latest commit should work.

**Comment by andrewnakas** [comment]
if you pull the new version and uncompress the file libgvrunity.a.zip you should be good to go. Let me know if this works, Thanks for catching that.

**Comment by latne1ec** [comment]
Works! Thanks for the help man

**Comment by andrewnakas** [comment]
Awesome! Happy prototyping
