### ISSUE TITLE
very low resolution in VR mode

### ISSUE THREAD

**Issue by Cfirote** [andrewnakas/ARKit-Cardboard-VR#2]
Hi and thank you for your work, it work like a charm 👍 

On the VR mode, the resolution is very low, can we change it ? (it's low for the camera image and the 3d model on the scene)

Regards.

**Comment by europeanrich** [comment]
Hi, this hack is amazing and has been a tremendous help. 

I found that if I changed the size of the quad material (new render texture) from 256x256 to 1024x1024 (or even 2048x2048) it will improve the resolution in VR mode.

**Comment by andrewnakas** [comment]
Hey! Thanks for the help in catching and solving this. The latest comit has the render texture set at 960x1080 and then the render texture is set at 8x9 to provide a distortion free higher res experience.
