### ISSUE TITLE
Xcode build error (iOS 11.0, Xcode 9.0.1, Unity 2017.2.0f3)

### ISSUE THREAD

**Issue by M4R5W0N6** [andrewnakas/ARKit-Cardboard-VR#5]
These are my current settings in both programs. Note that they held the default values from the ZIP.

**Unity**:
Scripting background set to IL2CPP
Target minimum iOS Version set to 11.0
Architecture set to Universal (which, I believe includes both ARMv7 as well as ARM64)

**Xcode**:
Architecture set to armv7 arm64
Supported platforms set to iphoneos
Devices set to Universal (includes iPhone + iPad)
Deployment target set to 11.0

When I build out to my iPhone 6s (running iOS 11.0) it displays this error:
"*invalid iOS deployment version '-miphoneos-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets*"

When I attempt to change the variables listed above (in either program) in the effort of making the build ARM64 only I am thrown 20 errors such as:
"*Unknown type name 'ARWorldTrackingSessionConfiguration'; did you mean 'ARKitWorldTrackingSessionConfiguration'?*" and
"*Member reference type 'ARKitWorldTrackingSessionConfiguration' is a pointer; did you mean to use '->'?*" and finally,
"*Too many errors emitted, stopping now*"

Tried again with Xcode 9.1 Beta, still nothing but errors. I'm getting the same problems here as I did with https://github.com/YclepticStudios/arkit-vr Is there some way in which I'm obviously butchering the build?

**Comment by M4R5W0N6** [comment]
It seems I missed the install instructions as I've managed to reduce the build errors to one after expanding libgvrunity.zip

**Comment by andrewnakas** [comment]
Ok just pushed an update to project with arkit 2.0 and pushed a build on my end with ios 12 and xcode 10. Let me know if this works for you.
