### ISSUE TITLE
Running fail on iPhone

### ISSUE THREAD

**Issue by kweimingxx** [andrewnakas/ARKit-Cardboard-VR#6]
I've integrated some of my project into yours
it build successfully on my iPhone but after running the app it stuck at some point on Xcode(line 33)
do you know how to fix that?
thanks!
![2018-04-14 4 12 47](https://user-images.githubusercontent.com/13203622/38755953-48de5452-3f9a-11e8-9d0f-bff6b5226487.png)

**Comment by andrewnakas** [comment]
Hmm can you build arkit apps normally? I would recommend to try to upgrade
the arkit version as it's most likely outdated if you are using the one
from github. I should prob push a new commit if I get around to it.

**Comment by andrewnakas** [comment]
Ok just pushed an update to project with arkit 2.0 and pushed a build on my end with ios 12 and xcode 10. Let me know if this works for you.
